import { Category, Product } from './types';

export const defaultCategories: Category[] = [
  { id: 'c_sets', name: 'Сеты', sortOrder: 1 },
  { id: 'c_rolls', name: 'Роллы', sortOrder: 2 },
  { id: 'c_baked', name: 'Запеченные', sortOrder: 3 },
  { id: 'c_tempura', name: 'Темпура', sortOrder: 4 },
  { id: 'c_pizza', name: 'Пицца', sortOrder: 5 },
  { id: 'c_wok', name: 'WOK лапша', sortOrder: 6 },
  { id: 'c_fastfood', name: 'Шаурма и бургеры', sortOrder: 7 },
  { id: 'c_snacks', name: 'Закуски и фри', sortOrder: 8 },
  { id: 'c_desserts', name: 'Десерты', sortOrder: 9 },
  { id: 'c_drinks', name: 'Напитки и кофе', sortOrder: 10 },
];

export const defaultProducts: Product[] = [
  // === СЕТЫ ===
  {
    id: 'set_santakki',
    categoryId: 'c_sets',
    name: 'Сет «Сан Такки»',
    description: 'Филадельфия классик, Калифорния с крабом, Запеченный с лососем, Темпура с курицей (32 шт, 1150г).',
    price: 1590,
    imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'set_hot',
    categoryId: 'c_sets',
    name: 'Сет «Горячий микс»',
    description: 'Запеченный с крабом, Запеченный с курочкой, Темпура с лососем, Темпура с креветкой (32 шт, 1200г).',
    price: 1390,
    imageUrl: 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'set_kilo',
    categoryId: 'c_sets',
    name: 'Сет «Килограмм»',
    description: 'Сбалансированный набор: классические, запеченные и темпура роллы на компанию (32 шт, ровно 1000г).',
    price: 1190,
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'set_phila',
    categoryId: 'c_sets',
    name: 'Сет «Филадельфия Мания»',
    description: 'Филадельфия Классик, Филадельфия с угрем, Филадельфия Лайт, Запеченная Филадельфия (32 шт).',
    price: 1790,
    imageUrl: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'set_tempura',
    categoryId: 'c_sets',
    name: 'Сет «Темпура Бум»',
    description: '4 вида горячих роллов в хрустящей панировке: Темпура Сяке, Темпура Эби, Темпура Чикен, Темпура Краб (32 шт).',
    price: 1350,
    imageUrl: 'https://images.unsplash.com/photo-1617196034183-421b4917c92d?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'set_mini',
    categoryId: 'c_sets',
    name: 'Сет «Мини / Студент»',
    description: 'Маки с лососем, Маки с крабом, Запеченный с цыпленком (24 шт, 680г). Отличный выбор для одного или двоих.',
    price: 790,
    imageUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&q=80&w=800',
  },

  // === КЛАССИЧЕСКИЕ РОЛЛЫ ===
  {
    id: 'roll_phila_classic',
    categoryId: 'c_rolls',
    name: 'Филадельфия Классик',
    description: 'Отборное филе лосося, нежный сливочный сыр Cremette, свежий огурец, рис, нори (8 шт, 260г).',
    price: 460,
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'roll_phila_deluxe',
    categoryId: 'c_rolls',
    name: 'Филадельфия Де-Люкс',
    description: 'Лосось покрывает ролл со всех сторон, увеличенная порция сливочного сыра, авокадо (8 шт, 290г).',
    price: 560,
    imageUrl: 'https://images.unsplash.com/photo-1562802379-bc22d6402ea8?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'roll_california',
    categoryId: 'c_rolls',
    name: 'Калифорния со снежным крабом',
    description: 'Снежный краб, свежий огурец, японский майонез, хрустящая икра тобико масаго (8 шт, 230г).',
    price: 380,
    imageUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'roll_california_shrimp',
    categoryId: 'c_rolls',
    name: 'Калифорния с креветкой',
    description: 'Тигровая креветка, сливочный сыр, огурец, икра масаго оранжевая (8 шт, 240г).',
    price: 420,
    imageUrl: 'https://images.unsplash.com/photo-1617196034096-76495d4ea583?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'roll_lava_salmon',
    categoryId: 'c_rolls',
    name: 'Лава с лососем',
    description: 'Филе лосося, сливочный сыр, огурец, фирменная шапочка из соуса Лава (8 шт, 250г).',
    price: 440,
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'roll_canada',
    categoryId: 'c_rolls',
    name: 'Канада с копченым угрем',
    description: 'Копченый угорь, лосось, сливочный сыр, огурец, соус унаги, жареный кунжут (8 шт, 260г).',
    price: 520,
    imageUrl: 'https://images.unsplash.com/photo-1615361200141-f45040f367be?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'roll_bonito',
    categoryId: 'c_rolls',
    name: 'Бонито с лососем',
    description: 'Лосось, сливочный сыр, огурец, стружка тунца бонито (8 шт, 230г).',
    price: 390,
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'roll_maki_salmon',
    categoryId: 'c_rolls',
    name: 'Маки с лососем',
    description: 'Классический мини-ролл со свежим филе лосося (8 шт, 120г).',
    price: 250,
    imageUrl: 'https://images.unsplash.com/photo-1562802379-bc22d6402ea8?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'roll_maki_cucumber',
    categoryId: 'c_rolls',
    name: 'Маки с огурцом и кунжутом',
    description: 'Свежий хрустящий огурец, кунжут, рис, нори (8 шт, 110г).',
    price: 170,
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&q=80&w=800',
  },

  // === ЗАПЕЧЕННЫЕ РОЛЛЫ ===
  {
    id: 'baked_salmon',
    categoryId: 'c_baked',
    name: 'Запеченный с лососем',
    description: 'Лосось, сливочный сыр, свежий огурец, фирменная запеченная сырная шапочка, соус унаги (8 шт, 280г).',
    price: 420,
    imageUrl: 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'baked_eel',
    categoryId: 'c_baked',
    name: 'Запеченный с угрем',
    description: 'Копченый угорь, сливочный сыр, спайси-сырный соус, унаги соус, белый кунжут (8 шт, 280г).',
    price: 490,
    imageUrl: 'https://images.unsplash.com/photo-1615361200141-f45040f367be?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'baked_shrimp',
    categoryId: 'c_baked',
    name: 'Запеченный с креветкой',
    description: 'Тигровая креветка, икра масаго, сыр, нежная сливочно-чесночная шапочка (8 шт, 270г).',
    price: 440,
    imageUrl: 'https://images.unsplash.com/photo-1617196034096-76495d4ea583?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'baked_crab',
    categoryId: 'c_baked',
    name: 'Запеченный Краб-Крем',
    description: 'Снежный краб, омлет тамаго, сыр, запеченный моцарелла соус, унаги (8 шт, 260г).',
    price: 350,
    imageUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'baked_chicken',
    categoryId: 'c_baked',
    name: 'Запеченный Чикен Спайси',
    description: 'Копченая курочка, спелые томаты, сыр Cremette, пикантный соус спайси (8 шт, 270г).',
    price: 360,
    imageUrl: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&q=80&w=800',
  },

  // === ТЕМПУРА РОЛЛЫ ===
  {
    id: 'tempura_salmon',
    categoryId: 'c_tempura',
    name: 'Темпура Сяке (с лососем)',
    description: 'Лосось, сливочный сыр, огурец, обжарен в хрустящих сухарях панко, унаги соус (8 шт, 290г).',
    price: 430,
    imageUrl: 'https://images.unsplash.com/photo-1617196034183-421b4917c92d?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'tempura_shrimp',
    categoryId: 'c_tempura',
    name: 'Темпура Эби (с креветкой)',
    description: 'Тигровая креветка, сливочный сыр, икра масаго, японский кляр панко, соус унаги (8 шт, 280г).',
    price: 440,
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'tempura_eel',
    categoryId: 'c_tempura',
    name: 'Темпура Унаги',
    description: 'Копченый угорь, сыр, авокадо, кляр темпура, ароматный соус унаги, кунжут (8 шт, 280г).',
    price: 480,
    imageUrl: 'https://images.unsplash.com/photo-1615361200141-f45040f367be?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'tempura_caesar',
    categoryId: 'c_tempura',
    name: 'Темпура Цезарь',
    description: 'Нежное филе цыпленка, салат айсберг, томаты, пармезан, сухари панко, соус цезарь (8 шт, 290г).',
    price: 380,
    imageUrl: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&q=80&w=800',
  },

  // === ПИЦЦА ===
  {
    id: 'pizza_pepperoni',
    categoryId: 'c_pizza',
    name: 'Пицца Пепперони',
    description: 'Острые колбаски пепперони, итальянский томатный соус, сыр моцарелла, орегано (32 см, 540г).',
    price: 550,
    imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'pizza_4cheeses',
    categoryId: 'c_pizza',
    name: 'Пицца «Четыре сыра»',
    description: 'Настоящее сырное изобилие: моцарелла, сыр дор блю, чеддер и пармезан на нежном сливочном соусе (32 см, 520г).',
    price: 590,
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'pizza_meat',
    categoryId: 'c_pizza',
    name: 'Пицца Мясное Ассорти',
    description: 'Пепперони, ветчина, сочный бекон, куриное филе, соус помодоро, двойная моцарелла (32 см, 620г).',
    price: 650,
    imageUrl: 'https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'pizza_carbonara',
    categoryId: 'c_pizza',
    name: 'Пицца Карбонара',
    description: 'Хрустящий бекон, сливочный соус, моцарелла, тертый пармезан, смесь итальянских трав (32 см, 560г).',
    price: 580,
    imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'pizza_ham_mushrooms',
    categoryId: 'c_pizza',
    name: 'Пицца Ветчина и грибы',
    description: 'Нежная ветчина, свежие шампиньоны, томатный соус, сыр моцарелла (32 см, 550г).',
    price: 520,
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'pizza_cheese_chicken',
    categoryId: 'c_pizza',
    name: 'Пицца Сырный цыпленок',
    description: 'Куриное филе, свежие томаты, сливочно-сырный соус чеддер, моцарелла (32 см, 560г).',
    price: 540,
    imageUrl: 'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&q=80&w=800',
  },

  // === WOK ЛАПША ===
  {
    id: 'wok_chicken_teriyaki',
    categoryId: 'c_wok',
    name: 'WOK Удон с курицей терияки',
    description: 'Пшеничный удон, сочное куриное филе, болгарский перец, цукини, морковь, кунжут, соус терияки (350г).',
    price: 360,
    imageUrl: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'wok_pork_sweet_sour',
    categoryId: 'c_wok',
    name: 'WOK со свининой в кисло-сладком',
    description: 'Яичная лапша, обжаренная свиная вырезка, ананас, сладкий перец, лук, кисло-сладкий соус (350г).',
    price: 380,
    imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'wok_seafood',
    categoryId: 'c_wok',
    name: 'WOK с морепродуктами',
    description: 'Гречневая лапша соба, тигровые креветки, кальмары, овощи, устричный соус, кунжут (350г).',
    price: 440,
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'wok_tyaskhan_rice',
    categoryId: 'c_wok',
    name: 'Тясхан с курицей (жареный рис)',
    description: 'Японский рис, обжаренный на воке с филе курочки, яйцом, овощами и темным кунжутным маслом (320г).',
    price: 340,
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&q=80&w=800',
  },

  // === ШАУРМА И БУРГЕРЫ ===
  {
    id: 'fastfood_shawarma_firm',
    categoryId: 'c_fastfood',
    name: 'Шаурма «San Takki» фирменная',
    description: 'Сочное мясо цыпленка на гриле, свежие томаты, огурцы, пекинская капуста, фирменный чесночный соус в хрустящем лаваше (420г).',
    price: 270,
    imageUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'fastfood_shawarma_cheese',
    categoryId: 'c_fastfood',
    name: 'Шаурма Сырная',
    description: 'Курочка с гриля, двойной сыр (моцарелла и чеддер), свежие овощи, авторский соус (440г).',
    price: 310,
    imageUrl: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'fastfood_burger_beef',
    categoryId: 'c_fastfood',
    name: 'Бургер с сочной говядиной',
    description: 'Котлета из 100% говядины, сыр чеддер, лист салата, спелый помидор, маринованный огурчик, бургер-соус (320г).',
    price: 340,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'fastfood_burger_crispy',
    categoryId: 'c_fastfood',
    name: 'Чикен Бургер Криспи',
    description: 'Хрустящее куриное филе в панировке, сыр чеддер, салат айсберг, нежный майо-соус (290г).',
    price: 290,
    imageUrl: 'https://images.unsplash.com/photo-1521305916504-4a1121188589?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'fastfood_hotdog',
    categoryId: 'c_fastfood',
    name: 'Хот-дог Датский',
    description: 'Французская булочка, сочная баварская сосиска, маринованные корнишоны, жареный лук фри, горчичный соус (240г).',
    price: 220,
    imageUrl: 'https://images.unsplash.com/photo-1619740455993-9e612b1af08a?auto=format&fit=crop&q=80&w=800',
  },

  // === ЗАКУСКИ И ФРИ ===
  {
    id: 'snack_onigiri_salmon',
    categoryId: 'c_snacks',
    name: 'Онигири с лососем и сыром',
    description: 'Традиционный японский треугольник из риса с начинкой из слабосоленого лосося и сыра Cremette в листе нори (130г).',
    price: 160,
    imageUrl: 'https://images.unsplash.com/photo-1617196034183-421b4917c92d?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'snack_onigiri_crab',
    categoryId: 'c_snacks',
    name: 'Онигири со снежным крабом',
    description: 'Рисовый онигири с сочной начинкой из снежного краба и легким спайси-соусом (130г).',
    price: 140,
    imageUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'snack_fries',
    categoryId: 'c_snacks',
    name: 'Картофель фри хрустящий',
    description: 'Золотистые ломтики картофеля фри со щепоткой морской соли (150г).',
    price: 160,
    imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'snack_wedges',
    categoryId: 'c_snacks',
    name: 'Картофель по-деревенски',
    description: 'Ароматные запеченные дольки картофеля с чесноком, паприкой и пряными травами (170г).',
    price: 180,
    imageUrl: 'https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'snack_nuggets',
    categoryId: 'c_snacks',
    name: 'Наггетсы куриные (8 шт)',
    description: 'Нежное филе цыпленка в хрустящей золотистой панировке (8 шт, 160г).',
    price: 210,
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'snack_cheese_sticks',
    categoryId: 'c_snacks',
    name: 'Сырные палочки Моцарелла',
    description: 'Тягучий расплавленный сыр моцарелла в хрустящей сухарной корочке (5 шт, 150г).',
    price: 240,
    imageUrl: 'https://images.unsplash.com/photo-1531749668029-2db88e4276c7?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'snack_shrimp_tempura',
    categoryId: 'c_snacks',
    name: 'Креветки темпура (5 шт)',
    description: 'Отборные королевские креветки в воздушном хрустящем кляре, подаются с соусом унаги (140г).',
    price: 350,
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800',
  },

  // === ДЕСЕРТЫ ===
  {
    id: 'dessert_cheesecake_classic',
    categoryId: 'c_desserts',
    name: 'Чизкейк «Нью-Йорк»',
    description: 'Классический нежный творожно-сливочный чизкейк на тонком песочном корже (120г).',
    price: 190,
    imageUrl: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'dessert_red_velvet',
    categoryId: 'c_desserts',
    name: 'Торт «Красный бархат»',
    description: 'Яркие бархатистые коржи с нежным сливочно-сырным кремом (130г).',
    price: 220,
    imageUrl: 'https://images.unsplash.com/photo-1586788680434-30d324b2d46f?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'dessert_medovik',
    categoryId: 'c_desserts',
    name: 'Торт «Медовик» домашний',
    description: 'Тонкие медовые коржи, пропитанные легким сметанным кремом (130г).',
    price: 180,
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'dessert_donuts',
    categoryId: 'c_desserts',
    name: 'Донат глазированный (клубничный)',
    description: 'Пышный американский пончик с клубничной глазурью и цветной кондитерской посыпкой (75г).',
    price: 95,
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'dessert_eclair',
    categoryId: 'c_desserts',
    name: 'Эклер со сливочным кремом',
    description: 'Французское заварное пирожное со взбитым сливочным кремом и шоколадной помадкой (70г).',
    price: 85,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
  },

  // === НАПИТКИ И КОФЕ ===
  {
    id: 'drink_cappuccino',
    categoryId: 'c_drinks',
    name: 'Капучино зерновой',
    description: 'Свежесваренный эспрессо из 100% арабики с пышной шелковистой молочной пенкой (300 мл).',
    price: 120,
    imageUrl: 'https://images.unsplash.com/photo-1572442388796-11668ba67e53?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'drink_latte',
    categoryId: 'c_drinks',
    name: 'Латте зерновой',
    description: 'Нежный кофейно-молочный напиток с мягким сливочным вкусом (350 мл).',
    price: 130,
    imageUrl: 'https://images.unsplash.com/photo-1593443320739-77f74939d0da?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'drink_americano',
    categoryId: 'c_drinks',
    name: 'Американо зерновой',
    description: 'Классический черный кофе из свежемолотых зерен с насыщенным ароматом (250 мл).',
    price: 99,
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'drink_mors',
    categoryId: 'c_drinks',
    name: 'Морс ягодный домашний',
    description: 'Натуральный освежающий морс из клюквы и брусники собственного приготовления (0.5 л).',
    price: 110,
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'drink_cola',
    categoryId: 'c_drinks',
    name: 'Добрый Кола',
    description: 'Освежающий газированный напиток (0.5 л, бутылочка).',
    price: 100,
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'drink_juice',
    categoryId: 'c_drinks',
    name: 'Сок «Добрый» в ассортименте',
    description: 'Яблочный, апельсиновый или вишневый сок (0.5 л).',
    price: 120,
    imageUrl: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&q=80&w=800',
  },
];
